#!/usr/bin/env python3
"""Render reviewed JSON into Markdown and browser data. Deterministic, no network."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(name: str) -> dict:
    return json.loads((ROOT / 'data' / f'{name}.json').read_text(encoding='utf-8'))


def header(title: str, date: str, source_urls: list[str]) -> str:
    return ('---\n' + f'title: {json.dumps(title)}\nlast_verified: {date}\n'
            'tool_version: "See individual entries and tool guides"\nverification: source-reviewed\n'
            'status: "GENERATED FROM REVIEWED DATA"\nsources:\n' +
            ''.join(f'  - {json.dumps(url)}\n' for url in source_urls) + '---\n\n' +
            f'# {title}\n\n> **Last verified:** {date} (source review). **Tool version:** see linked tool pages. '
            '[Runtime validation](../maintenance/validation.md) is recorded separately.\n\n'
            '<!-- Generated by scripts/render_data.py; edit data/ instead. -->\n\n')


def outputs() -> dict[str, str]:
    catalog, models, routes = read('catalog'), read('models'), read('routes')
    sources = {item['id']: item for item in read('sources')['sources']}
    urls = sorted({sources[s]['url'] for t in catalog['tools'] for s in t['sources']})
    compare = header('Compatibility database', catalog['verified_on'], urls)
    compare += ('<div id="compatibility-browser" class="atlas-widget" aria-label="Tool compatibility filters"></div>\n\n'
                '## Cost and providers\n\n'
                'OPEN SOURCE describes a license. FREE TIER describes limited model access. '
                'LOCAL describes inference location. Provider-documented does not mean tool-vendor certified. '
                '“Not established” means no reviewed support claim, not proof that an experiment is impossible.\n\n'
                '| Tool | Software | Model cost | Free tier | Local | OpenRouter | Ollama |\n'
                '| --- | --- | --- | --- | --- | --- | --- |\n')
    for t in catalog['tools']:
        compare += f"| [{t['name']}](../{t['guide']}) | {t['license']} | {t['model_cost']} | {t['free_tier']} | {'Yes, see route' if t['local'] else 'No reviewed local route'} | {t['openrouter']} | {t['ollama']} |\n"
    compare += ('\n## Platforms\n\n“Documented” reflects vendor instructions, not execution on every device. '
                'Android native support is never inferred from Linux. A cloud terminal inherits its host OS and resource limits.\n\n'
                '| Tool | Windows | Linux | macOS | Android | Cloud Shell / Linux host |\n'
                '| --- | --- | --- | --- | --- | --- |\n')
    for t in catalog['tools']:
        compare += '| ' + f"[{t['name']}](../{t['guide']}) | " + ' | '.join(t['platforms'].values()) + ' |\n'
    compare += '\n## Evidence per entry\n\n'
    for t in catalog['tools']:
        compare += f"- **{t['name']}** ({t['last_verified']}): " + ', '.join(f"[{sources[s]['title']}]({sources[s]['url']})" for s in t['sources']) + '.\n'
    compare += '\nSuggest a correction with the upstream source, installed version, OS/architecture, and a redacted reproduction.\n'
    model = header('Local model reference table', models['verified_on'], [m['source'] for m in models['models']])
    model += models['note'] + '\n\n| Model / source | Parameters | Quantization | Download | RAM planning estimate | Context caveat | Best learning use | Provider / availability |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n'
    for m in models['models']:
        model += f"| [{m['tag']}]({m['source']}) | {m['parameters']} | {m['quantization']} | {m['download']} | {m['ram_estimate']} | {m['context']} | {m['use']} | {m['provider']} |\n"
    model += '\nExact tags can change; inspect `ollama show TAG` and the model license. The 30B MoE still needs memory for its full weights. See [hardware](hardware.md) and [selection methodology](local-models.md). No performance benchmark is claimed.\n'
    return {'docs/getting-started/comparison.md': compare, 'docs/providers/model-table.md': model,
            'docs/assets/catalog.json': json.dumps(catalog, indent=2) + '\n',
            'docs/assets/routes.json': json.dumps(routes, indent=2) + '\n'}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if generated files differ; do not write')
    args = parser.parse_args()
    stale = []
    for relative, text in outputs().items():
        target = ROOT / relative
        if args.check:
            if not target.exists() or target.read_text(encoding='utf-8') != text:
                stale.append(relative)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding='utf-8')
    if stale:
        print('Regenerate with python scripts/render_data.py: ' + ', '.join(stale))
        return 1
    print('Generated data is current.' if args.check else 'Rendered compatibility, model, and route data.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
